#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	OpenBSD Secure Shell server
### END INIT INFO

set -e

. /lib/lsb/init-functions


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	sudo -u elasticsearch /opt/elasticsearch/bin/elasticsearch 
	;;
  stop)
	killall -9 /opt/elasticsearch/bin/elasticsearch
	;;

  reload|force-reload)
	;;

  restart)
	$0 stop
	$0 start
	;;

  try-restart)
	;;

  status)
	;;

  *)
	log_action_msg "Usage: /etc/init.d/elasticsearch {start|stop|reload|force-reload|restart|try-restart|status}"
	exit 1
esac

exit 0
